#!/usr/bin/env node
/**
 * Scans src/assets/ and generates src/assets/generated-assets.ts with one named
 * export per file.  Run via:  npm run generate:assets
 *
 * Naming rule: filename → remove extension → uppercase → non-alphanumeric → _
 *   icon-256.png   → ICON_256
 *   logo.svg       → LOGO
 *   brand-mark.webp → BRAND_MARK
 */

const fs = require('fs');
const path = require('path');

const ASSETS_DIR = path.join(__dirname, '../src/assets');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/generated-assets.ts');

const MIME_TYPES = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
};

function toConstName(filename) {
  return filename
    .replace(/\.[^.]+$/, '')       // strip extension
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')  // non-alphanumeric → underscore
    .replace(/^_+|_+$/g, '');     // trim leading/trailing underscores
}

function toDataUri(filepath) {
  const ext = path.extname(filepath).toLowerCase();
  const mime = MIME_TYPES[ext];
  if (!mime) return null;

  const data = fs.readFileSync(filepath);
  const b64 = data.toString('base64');
  const chunks = b64.match(/.{1,120}/g) || [];

  const lines = [];
  lines.push(`  "data:${mime};base64," +`);
  chunks.forEach((chunk, i) => {
    lines.push(`  "${chunk}"${i === chunks.length - 1 ? ';' : ' +'}`);
  });
  return lines.join('\n');
}

if (!fs.existsSync(ASSETS_DIR)) {
  console.error(`assets directory not found: ${ASSETS_DIR}`);
  process.exit(1);
}

const files = fs
  .readdirSync(ASSETS_DIR)
  .filter((f) => Object.keys(MIME_TYPES).includes(path.extname(f).toLowerCase()))
  .sort();

if (files.length === 0) {
  console.warn('No supported asset files found in src/assets/.');
  process.exit(0);
}

const sections = [
  '// Auto-generated by scripts/generate-assets.js',
  '// Do not edit manually — run `npm run generate:assets` to regenerate.',
  '',
];

const exported = [];

for (const file of files) {
  const uri = toDataUri(path.join(ASSETS_DIR, file));
  if (!uri) continue;

  const constName = toConstName(file);
  exported.push({ file, constName });

  sections.push(`// Source: src/assets/${file}`);
  sections.push(`export const ${constName} =`);
  sections.push(uri);
  sections.push('');
}

fs.writeFileSync(OUTPUT_FILE, sections.join('\n'));

console.log(`Generated ${OUTPUT_FILE}`);
exported.forEach(({ file, constName }) =>
  console.log(`  ${constName.padEnd(30)} ← src/assets/${file}`)
);
