// Copyright (c) 2025 Stephen J. Lu
// SPDX-License-Identifier: Apache-2.0

import { createPagesFunctionHandler } from '@react-router/cloudflare';
import { getLoadContext } from '../load-context';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
import * as build from '../build/server';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - temporary workaround for crossOrigin type issue
export const onRequest = createPagesFunctionHandler({ build, getLoadContext });
